version: '3'
services:
  react-app: 
    container_name: tdsr-front-end
    restart: always
    build: ./client
    ports:
      - '3000:3000'
    networks:
      - mern-app
  app:
    container_name: tdsr-server
    restart: always
    build: ./server
    env_file: ./server/config/dev.env
    ports:
      - '3001:3001'
    links:
      - mongo
    networks:
      - mern-app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes: 
  mongo-data:
    driver: local